apiVersion: v1
kind: Service
metadata:
  name: application-ott
  namespace: exp1-d
  labels: &id001
    app.kubernetes.io/name: application-ott
    app.kubernetes.io/part-of: ina-infra
    ina.lab/slice: '3'
    ina.lab/app-type: ott
    ina.lab/role: server
spec:
  type: ClusterIP
  selector: *id001
  ports:
  - name: web
    port: 80
    targetPort: 80
  - name: rtsp
    port: 8554
    targetPort: 8554
  - name: http
    port: 8080
    targetPort: 8080
  - name: metrics
    port: 9103
    targetPort: 9103
