apiVersion: v1
kind: Service
metadata:
  annotations:
    configmanagement.gke.io/managed: enabled
    configmanagement.gke.io/source-path: namespaces/backend-system/service-resource-backend-controller-grpc-svc.yaml
    configmanagement.gke.io/token: fa352451d6fec752b063f38b22c05ecb5aeda19c
    configsync.gke.io/git-context: '{"repo":"http://10.1.132.51:3000/nephio/mgmt.git","branch":"main","rev":"HEAD"}'
    configsync.gke.io/manager: :root_mgmt
    configsync.gke.io/resource-id: _service_backend-system_resource-backend-controller-grpc-svc
  labels:
    app.kubernetes.io/component: tbd
    app.kubernetes.io/instance: tbd
    app.kubernetes.io/managed-by: configmanagement.gke.io
    app.kubernetes.io/name: resource-backend
    app.kubernetes.io/part-of: resource-backend
    app.kubernetes.io/version: tbd
    configsync.gke.io/declared-version: v1
    fn.kptgen.dev/grpc: resource-backend-controller
  name: resource-backend-controller-grpc-svc
  namespace: backend-system
spec:
  ports:
  - name: grpc
    port: 9999
    protocol: TCP
    targetPort: 9999
  selector:
    fn.kptgen.dev/grpc: resource-backend-controller
  sessionAffinity: None
  type: ClusterIP
