apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: registry
  labels:
    app: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry:2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        env:
        - name: REGISTRY_HTTP_ADDR
          value: :5000
        - name: REGISTRY_STORAGE_DELETE_ENABLED
          value: "true"
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: /certs/tls.crt
        - name: REGISTRY_HTTP_TLS_KEY
          value: /certs/tls.key
        volumeMounts:
        - name: registry-vol
          mountPath: /var/lib/registry
        - name: registry-certs
          mountPath: /certs
          readOnly: true
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      - name: registry-console
        image: rubenmacedobarbosa/registry-console:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: web
          protocol: TCP
        env:
        - name: REGISTRY_URL
          value: localhost:5000
        - name: REGISTRY_USERNAME
          value: admin
        - name: REGISTRY_PASSWORD
          value: admin
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        - name: REGISTRY_NAME
          value: "Nephio Lab Registry"
        - name: AUTH_ENABLED
          value: "false"
        resources:
          limits:
            cpu: 300m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 64Mi
      volumes:
      - name: registry-vol
        persistentVolumeClaim:
          claimName: registry-pvc
      - name: registry-certs
        secret:
          secretName: registry-tls
