apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/ip-allocated-from-pool: mgmt-pool
    metallb.universe.tf/loadBalancerIPs: 10.1.132.30
  name: registry
  namespace: registry
spec:
  allocateLoadBalancerNodePorts: false
  ports:
  - name: registry
    port: 5000
    protocol: TCP
    targetPort: 5000
  - name: console
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: registry
  sessionAffinity: None
  type: LoadBalancer
