apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openspeedtest
  name: openspeedtest
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openspeedtest
  template:
    metadata:
      labels:
        app: openspeedtest
    spec:
      containers:
      - image: openspeedtest/latest:latest
        imagePullPolicy: Always
        name: openspeedtest
        ports:
        - containerPort: 3000
          protocol: TCP
        - containerPort: 3001
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
