apiVersion: v1
data:
  password: c2VjcmV0
  postgres-password: c2VjcmV0
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/managed-by: configmanagement.gke.io
    app.kubernetes.io/name: postgresql
  name: gitea-postgresql
  namespace: gitea
type: Opaque
