apiVersion: v1
data:
  password: c2VjcmV0
  username: bmVwaGlv
kind: Secret
metadata:
  labels:
    app.kubernetes.io/managed-by: configmanagement.gke.io
  name: git-user-secret
  namespace: gitea
type: kubernetes.io/basic-auth
