apiVersion: v1
data:
  _generals_: ''
  cache: QURBUFRFUj1tZW1jYWNoZQpFTkFCTEVEPXRydWUKSE9TVD1naXRlYS1tZW1jYWNoZWQuZ2l0ZWEuc3ZjLmNsdXN0ZXIubG9jYWw6MTEyMTE=
  database: REJfVFlQRT1wb3N0Z3JlcwpIT1NUPWdpdGVhLXBvc3RncmVzcWwuZ2l0ZWEuc3ZjLmNsdXN0ZXIubG9jYWw6NTQzMgpOQU1FPWdpdGVhClVTRVI9Z2l0ZWEKUEFTU1dEPXNlY3JldA==
  metrics: RU5BQkxFRD1mYWxzZQ==
  repository: Uk9PVD0vZGF0YS9naXQvZ2l0ZWEtcmVwb3NpdG9yaWVz
  security: SU5TVEFMTF9MT0NLPXRydWU=
  server: QVBQX0RBVEFfUEFUSD0vZGF0YQpET01BSU49MTAuMS4xMzIuNTEKRU5BQkxFX1BQUk9GPWZhbHNlCkhUVFBfUE9SVD0zMDAwClBST1RPQ09MPWh0dHAKUk9PVF9VUkw9aHR0cDovLzEwLjEuMTMyLjUxClNTSF9ET01BSU49MTAuMS4xMzIuNTEKU1NIX0xJU1RFTl9QT1JUPTIyClNTSF9QT1JUPTIy
  webhook: QUxMT1dFRF9IT1NUX0xJU1Q9KgpTS0lQX1RMU19WRVJJRlk9dHJ1ZQ==
kind: Secret
metadata:
  labels:
    app: gitea
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/managed-by: configmanagement.gke.io
    app.kubernetes.io/name: gitea
  name: gitea-inline-config
  namespace: gitea
type: Opaque
