apiVersion: v1
kind: Service
metadata:
  annotations:
    configmanagement.gke.io/managed: enabled
    configmanagement.gke.io/source-path: namespaces/gitea/service-gitea.yaml
    configmanagement.gke.io/token: fa352451d6fec752b063f38b22c05ecb5aeda19c
    configsync.gke.io/git-context: '{"repo":"http://10.1.132.51:3000/nephio/mgmt.git","branch":"main","rev":"HEAD"}'
    configsync.gke.io/manager: :root_mgmt
    configsync.gke.io/resource-id: _service_gitea_gitea
    metallb.universe.tf/loadBalancerIPs: 10.1.132.51
  labels:
    app: gitea
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/managed-by: configmanagement.gke.io
    app.kubernetes.io/name: gitea
    configsync.gke.io/declared-version: v1
  name: gitea
  namespace: gitea
spec:
  allocateLoadBalancerNodePorts: false
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  - name: http-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/name: gitea
  sessionAffinity: None
  type: LoadBalancer
