apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/ip-allocated-from-pool: local-pool
    metallb.universe.tf/loadBalancerIPs: 10.1.132.51
  labels:
    app: gitea
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/name: gitea
  name: gitea
  namespace: gitea
spec:
  allocateLoadBalancerNodePorts: false
  clusterIP: 10.106.177.200
  clusterIPs:
  - 10.106.177.200
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  - name: http-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/name: gitea
  sessionAffinity: None
  type: LoadBalancer
