apiVersion: v1
kind: Service
metadata:
  annotations:
    configmanagement.gke.io/managed: enabled
    configmanagement.gke.io/source-path: namespaces/gitea/service-gitea-memcached.yaml
    configmanagement.gke.io/token: fa352451d6fec752b063f38b22c05ecb5aeda19c
    configsync.gke.io/git-context: '{"repo":"http://10.1.132.51:3000/nephio/mgmt.git","branch":"main","rev":"HEAD"}'
    configsync.gke.io/manager: :root_mgmt
    configsync.gke.io/resource-id: _service_gitea_gitea-memcached
  labels:
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/managed-by: configmanagement.gke.io
    app.kubernetes.io/name: memcached
    configsync.gke.io/declared-version: v1
  name: gitea-memcached
  namespace: gitea
spec:
  ports:
  - name: memcache
    port: 11211
    protocol: TCP
    targetPort: memcache
  selector:
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/name: memcached
  sessionAffinity: None
  type: ClusterIP
