apiVersion: v1
kind: Service
metadata: # kpt-merge: gitea/gitea
  name: gitea
  namespace: gitea
  labels:
    app: gitea
    app.kubernetes.io/name: gitea
    app.kubernetes.io/instance: gitea
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.1.132.51
    internal.kpt.dev/upstream-identifier: '|Service|gitea|gitea'
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  ports:
  - name: ssh
    port: 22
    targetPort: 22
    protocol: TCP
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  - name: http-3000
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/instance: gitea
