apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: exp1-c
  labels:
    app: mysql
    app.kubernetes.io/part-of: ina-infra
    app.kubernetes.io/component: dedicated-core
type: Opaque
data:
  # linux / test (same as shared oai-cn)
  mysql-root-password: bGludXg=
  mysql-password: dGVzdA==
