apiVersion: v1
kind: ConfigMap
metadata:
  name: oai-udm-nf-conf
  namespace: exp1-c
  labels:
    app.kubernetes.io/part-of: ina-infra
    app.kubernetes.io/component: oai-controller
data:
  udm.yaml: "# Log level\nlog_level:\n  udm: {{ conf['logLevel'] }}\nregister_nf:\n\
    \  udm: 'yes'\nhttp_version: 2  # allowed value 1 and 2, make sure all NFs use\
    \ the same HTTP version\n############## SBI Interfaces\n### Each NF takes its\
    \ local SBI interfaces and remote interfaces from here, unless it gets them using\
    \ NRF discovery mechanisms\nnfs:\n  udm:\n    host: {{ conf['fqdn']['udm'] }}\n\
    \    sbi:\n      port: 80\n      api_version: v1\n      interface_name: {{ conf['nfInterfaces']['sbi']\
    \ }}\n  udr:\n    host: {{ conf['fqdn']['udr'] }}\n    sbi:\n      port: 80\n\
    \      api_version: v1\n  nrf:\n    host: {{ conf['fqdn']['nrf'] }}\n    sbi:\n\
    \      port: 80\n      api_version: v1\n############## NF-specific configuration\n\
    udm:\n  udm_name: \"OAI-UDM\"\n"
