apiVersion: v1
kind: ConfigMap
metadata:
  name: oai-ausf-op-conf
  namespace: exp1-c
  labels:
    app.kubernetes.io/part-of: ina-infra
    app.kubernetes.io/component: oai-controller
data:
  ausf.yaml: "nfInterfaces:\n  sbi: 'eth0'\nports: \n  - name: 'http'\n    port: 80\n\
    \    protocol: TCP\ncompute:\n  req:\n    cpu: '100m'\n    memory: '256Mi'\n \
    \ limits:\n    cpu: '100m'\n    memory: '256Mi'\nlogLevel: info\nimage: 'docker.io/oaisoftwarealliance/oai-ausf:v2.2.1'\n\
    fqdn:\n  udm: oai-udm\n  nrf: 'oai-nrf'\n"
