apiVersion: v1
kind: ConfigMap
metadata:
  name: ina-exp4-scheme
  namespace: exp4-s2
  labels:
    app.kubernetes.io/name: ina-exp4-scheme
    app.kubernetes.io/part-of: exp4
    ina.lab/scheme: exp4-s2
data:
  scheme: exp4-s2
  pl: "true"
  pm: "true"
  ps: "false"
  prb_policy: equal
  compute_policy: pm-resize
