apiVersion: v1
kind: Service
metadata:
  name: nws-xapp
  namespace: oai-slice-deployment
  labels:
    app.kubernetes.io/name: nws-xapp
spec:
  type: ClusterIP
  externalIPs:
  - 10.1.132.230
  selector:
    app.kubernetes.io/name: nws-xapp
  ports:
  - name: http
    port: 18080
    targetPort: 18080
    protocol: TCP
