apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: ue1-sim-rf
  namespace: oai-slice-deployment
spec:
  config: '{"cniVersion": "0.3.1", "name": "ue1-sim-rf", "plugins": [{"type": "macvlan",
    "capabilities": {"ips": true}, "master": "enp4s0f0", "mode": "bridge", "ipam":
    {"type": "static", "addresses": [{"address": "10.1.139.115/24", "gateway": "10.1.139.1"}]}},
    {"type": "tuning", "capabilities": {"mac": true}, "ipam": {}, "sysctl": {"net.ipv4.conf.IFNAME.arp_ignore":
    "1", "net.ipv4.conf.IFNAME.arp_announce": "2"}}]}'
