apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-ue-4
  namespace: oai-slice-deployment
  labels:
    app.kubernetes.io/name: oai-ue-4
    slice: '4'
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: oai-ue-4
  template:
    metadata:
      labels:
        app: oai-ue-4
        app.kubernetes.io/name: oai-ue-4
        slice: '4'
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{"name": "ue4-sim-rf", "interface": "rf", "ips":
          ["10.1.139.118/24"], "gateways": ["10.1.139.1"]}]'
    spec:
      serviceAccountName: oai-ue-4-sa
      terminationGracePeriodSeconds: 5
      nodeSelector:
        kubernetes.io/hostname: usrp
      containers:
      - name: ue
        image: 10.1.132.30:5000/oai-nr-ue:nws-v0.5-amd64
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        env:
        - name: USE_ADDITIONAL_OPTIONS
          value: -r 133 --numerology 1 -C 3325620000 --ssb 144 --rfsim --log_config.global_log_options
            level,nocolor,time --rfsimulator.serveraddr 10.1.139.114
        - name: TZ
          value: Europe/Paris
        volumeMounts:
        - name: configuration
          mountPath: /opt/oai-nr-ue/etc/nr-ue.conf
          subPath: ue.conf
      volumes:
      - name: configuration
        configMap:
          name: oai-ue-4-configmap
