apiVersion: apps/v1
kind: Deployment
metadata:
  name: function-runner
  namespace: porch-system
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: function-runner
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: function-runner
    spec:
      containers:
      - command:
        - /home/nonroot/server
        - -functions=/home/nonroot/functions
        - -pod-namespace=porch-fn-system
        - -max-request-body-size=6291456
        - -warm-up-pod-cache
        env:
        - name: WRAPPER_SERVER_IMAGE
          value: docker.io/nephio/porch-wrapper-server:latest
        image: docker.io/nephio/porch-function-runner:latest
        imagePullPolicy: IfNotPresent
        name: function-runner
        ports:
        - containerPort: 9445
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /home/nonroot/grpc-health-probe
            - -addr
            - localhost:9445
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 125m
            memory: 64Mi
        securityContext:
          runAsGroup: 10001
          runAsNonRoot: true
          runAsUser: 10001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /pod-cache-config
          name: pod-cache-config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: porch-fn-runner
      serviceAccountName: porch-fn-runner
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: pod-cache-config
        name: pod-cache-config-volume
