apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/managed-by: configmanagement.gke.io
  name: aggregated-apiserver-role
  namespace: porch-system
rules:
- apiGroups:
  - ''
  resources:
  - serviceaccounts
  verbs:
  - get
- apiGroups:
  - ''
  resources:
  - serviceaccounts/token
  verbs:
  - create
