apiVersion: v1
kind: Service
metadata:
  annotations:
    configmanagement.gke.io/managed: enabled
    configmanagement.gke.io/source-path: namespaces/porch-system/service-api.yaml
    configmanagement.gke.io/token: fa352451d6fec752b063f38b22c05ecb5aeda19c
    configsync.gke.io/git-context: '{"repo":"http://10.1.132.51:3000/nephio/mgmt.git","branch":"main","rev":"HEAD"}'
    configsync.gke.io/manager: :root_mgmt
    configsync.gke.io/resource-id: _service_porch-system_api
  labels:
    app.kubernetes.io/managed-by: configmanagement.gke.io
    configsync.gke.io/declared-version: v1
  name: api
  namespace: porch-system
spec:
  ports:
  - name: api
    port: 443
    protocol: TCP
    targetPort: 4443
  - name: webhooks
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: porch-server
  sessionAffinity: None
  type: ClusterIP
