apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: porch-system
spec:
  clusterIP: 10.110.212.73
  clusterIPs:
  - 10.110.212.73
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: api
    port: 443
    protocol: TCP
    targetPort: 4443
  - name: webhooks
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: porch-server
  sessionAffinity: None
  type: ClusterIP
