apiVersion: v1
kind: ConfigMap
metadata:
  name: ina-slice-2-ips
  namespace: exp1-a
  labels:
    app.kubernetes.io/part-of: ina-infra
    ina-infra.nephio.lab/slice: "2"
data:
  slice_id: "2"
  n: "2"
  upf_n3: "10.1.140.22"
  upf_n4: "10.1.140.42"
  upf_n6: "dhcp:10.1.137.0/24"
  cuup_e1: "10.1.140.82"
  cuup_f1u: "10.1.140.102"
  cuup_n3: "10.1.140.122"
  ue_rf: "10.1.140.142"
  dnn_cidr: "10.140.2.0/24"
  site_cu: "Edge"
  site_upf: "Edge"
  site_app: "Edge"
  cluster_cu: "edge"
  cluster_upf: "edge"
  peers: |
    CU-UP E1 -> CU-CP E1 10.1.140.202
    CU-UP N3 -> UPF N3 10.1.140.22
    UPF N4 -> SMF N4 10.1.140.12
    UPF N6 -> DHCP on Multus (Glass 10.1.137.0/24, gw 10.1.137.1)
    UE RF -> DU RF 10.1.140.204:4043
