apiVersion: v1
kind: ConfigMap
metadata:
  name: oai-flexric-configmap
  namespace: exp1-a
  labels:
    app.kubernetes.io/part-of: ina-infra
data:
  flexric.conf: '[NEAR-RIC]

    NEAR_RIC_IP = 10.1.140.205


    [XAPP]

    DB_DIR = /tmp/

    DB_NAME = xapp_db

    '
