apiVersion: v1
kind: Secret
metadata:
  name: ina-hf-token
  namespace: exp1-a
  labels:
    app.kubernetes.io/name: ina-hf-token
    app.kubernetes.io/part-of: ina-infra
    ina.lab/role: hf-token
type: Opaque
stringData:
  token: ""
