apiVersion: v1
kind: ConfigMap
metadata:
  name: oai-upf-op-conf
  namespace: exp1-c
  labels:
    app.kubernetes.io/part-of: ina-infra
    app.kubernetes.io/component: oai-controller
data:
  upf.yaml: "nad: \n  parent: 'enp7s0'\n  create: False\nports:\n  - name: 'n3n9'\n\
    \    port: 2152\n    protocol: UDP\n  - name: 'n4'\n    port: 8805\n    protocol:\
    \ UDP\n  - name: 'sbi'\n    port: 80\n    protocol: TCP\nnfInterfaces:\n  sbi:\
    \ 'n4'\n  n3: 'n3'\n  n4: 'n4'\n  n6: 'n6'\n  n9: 'eth0'\ncompute:\n  req:\n \
    \   cpu: '100m'\n    memory: '512Mi'\n  limits:\n    cpu: '100m'\n    memory:\
    \ '512Mi'\nlogLevel: debug\nimage: 'docker.io/oaisoftwarealliance/oai-upf:v2.2.1'\n\
    fqdn:\n  nrf: '10.1.140.11'\n  smf: '10.1.140.12'\n"
