apiVersion: v1
kind: ConfigMap
metadata:
  name: ina-slice-1-ips
  namespace: exp1-a
  labels:
    app.kubernetes.io/part-of: ina-infra
    ina-infra.nephio.lab/slice: "1"
data:
  slice_id: "1"
  n: "1"
  upf_n3: "10.1.140.21"
  upf_n4: "10.1.140.41"
  upf_n6: "dhcp:10.1.137.0/24"
  cuup_e1: "10.1.140.81"
  cuup_f1u: "10.1.140.101"
  cuup_n3: "10.1.140.121"
  ue_rf: "10.1.140.141"
  dnn_cidr: "10.140.1.0/24"
  site_cu: "Edge"
  site_upf: "Regional"
  site_app: "Regional"
  cluster_cu: "edge"
  cluster_upf: "regional"
  peers: |
    CU-UP E1 -> CU-CP E1 10.1.140.202
    CU-UP N3 -> UPF N3 10.1.140.21
    UPF N4 -> SMF N4 10.1.140.12
    UPF N6 -> DHCP on Multus (Glass 10.1.137.0/24, gw 10.1.137.1)
    UE RF -> DU RF 10.1.140.204:4043
