apiVersion: ref.nephio.org/v1alpha1
kind: Config
metadata:
  name: cuup-edge-cucp-regional
  namespace: oai-ran-cuup
spec:
  config:
    apiVersion: workload.nephio.org/v1alpha1
    kind: NFDeployment
    metadata:
      name: cucp-regional
      namespace: oai-ran-cucp
    spec:
      provider: cucp.openairinterface.org
      interfaces:
      - name: e1
        ipv4:
          address: 172.4.0.252/24
          gateway: 172.4.0.1
        vlanID: 6
