apiVersion: ref.nephio.org/v1alpha1
kind: Config
metadata:
  name: cuup-edge-upf-central
  namespace: oai-ran-cuup
spec:
  config:
    apiVersion: workload.nephio.org/v1alpha1
    kind: NFDeployment
    metadata:
      name: upf-core
      namespace: oai-upf
    spec:
      provider: upf.openairinterface.org
      interfaces:
      - name: n3
        ipv4:
          address: 172.3.0.254/24
          gateway: 172.3.0.1
        vlanID: 4
