apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata:
  name: ausf-core
  namespace: ina-infra
  labels:
    app.kubernetes.io/part-of: ina-infra
    app.kubernetes.io/component: dedicated-core
spec:
  provider: ausf.openairinterface.org
