apiVersion: workload.nephio.org/v1alpha1
kind: NFConfig
metadata:
  name: smf-core-config
  namespace: ina-infra
  labels:
    app.kubernetes.io/part-of: ina-infra
    app.kubernetes.io/component: dedicated-core
spec:
  configRefs:
  - apiVersion: cellular.nephio.org/v1alpha1
    kind: PLMN
    metadata:
      name: ina-infra-plmn
    spec:
      plmnInfo:
      - plmnID:
          mcc: '001'
          mnc: '01'
        tac: 81
        nssai:
        - sst: 1
          sd: FFFFFF
          dnnInfo:
          - name: oai
            sessionType: ipv4
            dns: 1.1.1.1
            subnet: 10.0.0.0/24

        - sst: 1
          sd: '000001'
          dnnInfo:
          - name: oai1
            sessionType: ipv4
            dns: 1.1.1.1
            subnet: 10.140.1.0/24

        - sst: 1
          sd: '000002'
          dnnInfo:
          - name: oai2
            sessionType: ipv4
            dns: 1.1.1.1
            subnet: 10.140.2.0/24

        - sst: 1
          sd: '000003'
          dnnInfo:
          - name: oai3
            sessionType: ipv4
            dns: 1.1.1.1
            subnet: 10.140.3.0/24

        - sst: 1
          sd: '000004'
          dnnInfo:
          - name: oai4
            sessionType: ipv4
            dns: 1.1.1.1
            subnet: 10.140.4.0/24

