apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: cuup5-n3
  namespace: ina-infra
  labels:
    app.kubernetes.io/part-of: ina-infra
    ina-infra.nephio.lab/role: cuup_n3

    ina-infra.nephio.lab/slice: "5"

spec:
  config: '{"cniVersion": "0.3.1", "name": "cuup5-n3", "plugins": [{"type": "macvlan", "capabilities": {"ips": true}, "master": "enp7s0", "mode": "bridge", "ipam": {"type": "static", "addresses": [{"address": "10.1.140.125/24", "gateway": "10.1.140.1"}]}}, {"type": "tuning", "capabilities": {"mac": true}, "ipam": {}, "sysctl": {"net.ipv4.conf.IFNAME.arp_ignore": "1", "net.ipv4.conf.IFNAME.arp_announce": "2"}}]}'
