apiVersion: v1
kind: ConfigMap
metadata:
  name: oai-amf-nf-conf
  namespace: ina-infra
  labels:
    app.kubernetes.io/part-of: ina-infra
    app.kubernetes.io/component: oai-controller
data:
  amf.yaml: "# Log level for all the NFs\nlog_level:\n  amf: {{ conf['logLevel'] }}\n\
    # If you enable registration, the other NFs will use the NRF discovery mechanism\n\
    register_nf:\n  amf: yes\nhttp_version: 2\n## general single_nssai configuration\n\
    ## Defines YAML anchors, which are reused in the config file\nsnssais:\n  {%-\
    \ for i in conf['PLMN']['plmnInfo']%}\n  {%- for s in i['nssai']%}\n  - &slice_{{\
    \ i['nssai'].index(s) }}\n    sst: {{ s['sst'] }}\n    sd: \"{{ s['sd'] if 'sd'\
    \ in s.keys() else 'FFFFFF' }}\"\n  {%- endfor %}\n  {%- endfor %}\n##############\
    \ SBI Interfaces\nnfs:\n  amf:\n    host: {{ conf['fqdn']['amf'] }}  #will be\
    \ replaced by service name\n    sbi:\n      port: 80\n      api_version: v1\n\
    \      interface_name: {{ conf['nfInterfaces']['sbi'] }}\n    n2:\n      interface_name:\
    \ {{ conf['nfInterfaces']['n2'] }}\n      port: 38412\n  smf:\n    host: {{ conf['fqdn']['smf']\
    \ }}\n    sbi:\n      port: 80\n      api_version: v1\n  udm:\n    host: {{ conf['fqdn']['udm']\
    \ }}\n    sbi:\n      port: 80\n      api_version: v1\n  ausf:\n    host: {{ conf['fqdn']['ausf']\
    \ }}\n    sbi:\n      port: 80\n      api_version: v1\n  nrf:\n    host: {{ conf['fqdn']['nrf']\
    \ }}\n    sbi:\n      port: 80\n      api_version: v1\n############## NF-specific\
    \ configuration\namf:\n  amf_name: {{ conf['amfName'] }}\n  # This really depends\
    \ on if we want to keep the \"mini\" version or not\n  support_features_options:\n\
    \    enable_simple_scenario: no # \"no\" by default with the normal deployment\
    \ scenarios with AMF/SMF/UPF/AUSF/UDM/UDR/NRF.\n                             \
    \  # set it to \"yes\" to use with the minimalist deployment scenario (including\
    \ only AMF/SMF/UPF) by using the internal AUSF/UDM implemented inside AMF.\n \
    \                              # There's no NRF in this scenario, SMF info is\
    \ taken from \"nfs\" section.\n    enable_nssf: no\n    enable_smf_selection:\
    \ yes\n  relative_capacity: 30\n  statistics_timer_interval: 20  # in seconds\n\
    \  emergency_support: false\n  served_guami_list:\n  {%- for i in conf['ServedGUAMI']%}\n\
    \    - mcc: {{ i['plmnID']['mcc'] }}\n      mnc: {{ i['plmnID']['mnc'] }}\n  \
    \    amf_region_id: {{ i['amfID']['amfRegionID'] }}\n      amf_set_id: {{ i['amfID']['amfSetID']\
    \ }}\n      amf_pointer: {{ i['amfID']['amfPointer'] }}\n  {%- endfor %}\n  plmn_support_list:\n\
    \  {%- for i in conf['PLMN']['plmnInfo']%}\n    - mcc: {{ i['plmnID']['mcc'] }}\n\
    \      mnc: {{ i['plmnID']['mnc'] }}\n      tac: {{ i['tac'] }}\n      nssai:\n\
    \        {%- for x in i['nssai'] %}\n        - *slice_{{ i['nssai'].index(x) }}\n\
    \        {%- endfor %}\n  {%- endfor %}\n  supported_integrity_algorithms:\n \
    \   - \"NIA1\"\n    - \"NIA2\"\n  supported_encryption_algorithms:\n    - \"NEA0\"\
    \n    - \"NEA1\"\n    - \"NEA2\"\n"
