apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata:
  name: gnb-edge
  namespace: oai-ran-gnb
spec:
  provider: du.openairinterface.org
  interfaces:
  - name: f1
    ipv4:
      address: 10.1.139.113/24
      gateway: 10.1.139.1
    vlanID: 5
  networkInstances:
  - name: vpc-cudu-f1
    interfaces:
    - f1
  parametersRefs:
  - name: gnb-edge-config
    apiVersion: workload.nephio.org/v1alpha1
    kind: NFConfig
