apiVersion: v1
kind: Namespace
metadata:
  name: exp4-s0
  labels:
    app.kubernetes.io/name: exp4-s0
    app.kubernetes.io/part-of: exp4
    ina.lab/scheme: exp4-s0
    ina.lab/pl: "false"
    ina.lab/pm: "false"
    ina.lab/ps: "false"
