apiVersion: v1
kind: ConfigMap
metadata:
  name: ina-exp4-scheme
  namespace: exp4-s0
  labels:
    app.kubernetes.io/name: ina-exp4-scheme
    app.kubernetes.io/part-of: exp4
    ina.lab/scheme: exp4-s0
data:
  scheme: exp4-s0
  pl: "false"
  pm: "false"
  ps: "false"
  prb_policy: equal
  compute_policy: frozen-peak
