apiVersion: v1
kind: Service
metadata:
  name: oai-du
  namespace: oai-ran-du
  labels:
    app.kubernetes.io/name: oai-du
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: oai-du
  ports:
  - name: f1c
    port: 38472
    protocol: SCTP
    targetPort: 38472
  - name: f1u
    port: 2152
    protocol: UDP
    targetPort: 2152
