apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: oai-cn
  labels:
    app: mysql
    chart: mysql-8.0.31
    release: mysql
    heritage: Helm
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: mysql
