apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata:
  name: amf-core
  namespace: oai-cn
spec:
  provider: amf.openairinterface.org
  capacity:
    maxSubscribers: 64
  interfaces:
  - name: n2
    ipv4:
      address: 10.1.138.102/24
      gateway: 10.1.138.1
    vlanID: 4
  networkInstances:
  - name: vpc-ran
    interfaces:
    - n2
  parametersRefs:
  - name: amf-core-config
    apiVersion: workload.nephio.org/v1alpha1
    kind: NFConfig
