apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata:
  name: smf-core
  namespace: oai-cn
spec:
  provider: smf.openairinterface.org
  capacity:
    maxNFConnections: 5
    maxSessions: 500
  interfaces:
  - name: n4
    ipv4:
      address: 10.1.139.12/24
      gateway: 10.1.139.1
    vlanID: 2
  networkInstances:
  - name: vpc-internal
    interfaces:
    - n4
  parametersRefs:
  - name: smf-core-config
    apiVersion: workload.nephio.org/v1alpha1
    kind: NFConfig
  - name: smf-core-upf-slice-1
    apiVersion: ref.nephio.org/v1alpha1
    kind: Config
  - name: smf-core-upf-slice-2
    apiVersion: ref.nephio.org/v1alpha1
    kind: Config
  - name: smf-core-upf-slice-3
    apiVersion: ref.nephio.org/v1alpha1
    kind: Config
  - name: smf-core-upf-slice-4
    apiVersion: ref.nephio.org/v1alpha1
    kind: Config
  - name: smf-core-upf-slice-5
    apiVersion: ref.nephio.org/v1alpha1
    kind: Config
