apiVersion: v1
kind: ConfigMap
metadata:
  name: oai-nrf-op-conf
  namespace: oai-cn-operators
data:
  nrf.yaml: "nfInterfaces:\n  sbi: 'eth0'\nports:\n  - name: 'http'\n    port: 80\n\
    \    protocol: TCP\ncompute:\n  req:\n    cpu: '100m'\n    memory: '256Mi'\n \
    \ limits:\n    cpu: '100m'\n    memory: '256Mi'\nlogLevel: info\nimage: 'docker.io/oaisoftwarealliance/oai-nrf:v2.0.1'\n\
    nfInterfaces:\n  sbi: 'eth0'\nports:\n  - name: 'http'\n    port: 80\n    protocol:\
    \ TCP\n"
