apiVersion: v1
kind: Service
metadata:
  name: application-iot
  namespace: ina-infra
  labels: &id001
    app.kubernetes.io/name: application-iot
    app.kubernetes.io/part-of: ina-infra
    ina.lab/slice: '4'
    ina.lab/app-type: iot
    ina.lab/role: server
spec:
  type: ClusterIP
  selector: *id001
  ports:
  - name: mqtt
    port: 1883
    targetPort: 1883
  - name: dashboard
    port: 80
    targetPort: 80
  - name: metrics
    port: 9105
    targetPort: 9105
