apiVersion: v1
kind: ServiceAccount
metadata:
  name: application-iot
  namespace: ina-infra
  labels:
    app.kubernetes.io/name: application-iot
    app.kubernetes.io/part-of: ina-infra
    ina.lab/slice: '4'
    ina.lab/app-type: iot
    ina.lab/role: server
