apiVersion: v1
kind: ConfigMap
metadata:
  name: oai-udr-nf-conf
  namespace: exp1-b
  labels:
    app.kubernetes.io/part-of: ina-infra
    app.kubernetes.io/component: oai-controller
data:
  udr.yaml: "# Log level\nlog_level:\n  udr: {{ conf['logLevel'] }}\n# If you enable\
    \ registration, the NF will use the NRF discovery mechanism\nregister_nf:\n  udr:\
    \ 'yes'\nhttp_version: 2  # allowed value 1 and 2, make sure all NFs use the same\
    \ HTTP version\n############## SBI Interfaces\n### Each NF takes its local SBI\
    \ interfaces and remote interfaces from here, unless it gets them using NRF discovery\
    \ mechanisms\nnfs:\n  udr:\n    host: {{ conf['fqdn']['udr'] }}\n    sbi:\n  \
    \    port: 80\n      api_version: v1\n      interface_name: {{ conf['nfInterfaces']['sbi']\
    \ }}\n  nrf:\n    host: {{ conf['fqdn']['nrf'] }}\n    sbi:\n      port: 80\n\
    \      api_version: v1\n############## NF-specific configuration\nudr:\n  udr_name:\
    \ \"OAI-UDR\"\ndatabase:\n  host: {{ conf['database']['host'] }}\n  user: {{ conf['database']['user']\
    \ }}\n  type: {{ conf['database']['type'] }}\n  password: {{ conf['database']['pass']\
    \ }}\n  database_name: oai_db\n  generate_random: true\n  connection_timeout:\
    \ {{ conf['database']['connection_timeout'] }} # seconds\n"
