apiVersion: v1
kind: ConfigMap
metadata:
  name: gpu-operator-node-feature-discovery-worker-conf
  namespace: gpu-operator
  labels:
    helm.sh/chart: node-feature-discovery-0.18.3
    app.kubernetes.io/name: node-feature-discovery
    app.kubernetes.io/instance: gpu-operator
    app.kubernetes.io/version: v0.18.3
    app.kubernetes.io/managed-by: Helm
data:
  nfd-worker.conf: "sources:\n  pci:\n    deviceClassWhitelist:\n    - \"02\"\n  \
    \  - \"0200\"\n    - \"0207\"\n    - \"0300\"\n    - \"0302\"\n    deviceLabelFields:\n\
    \    - vendor"
