apiVersion: v1
kind: ServiceAccount
metadata:
  name: gpu-operator
  namespace: gpu-operator
  labels:
    app.kubernetes.io/name: gpu-operator
    helm.sh/chart: gpu-operator-v26.3.3
    app.kubernetes.io/instance: gpu-operator
    app.kubernetes.io/version: v26.3.3
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: gpu-operator
