apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node0-bulk
  namespace: local-bulk
  labels:
    app.kubernetes.io/name: node0-bulk
    nephio.org/bulk-node: "regional-0"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1800Gi
