apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: ina-infra
  labels:
    app: mysql
    app.kubernetes.io/part-of: ina-infra
    app.kubernetes.io/component: dedicated-core
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: local-path
