apiVersion: v1
kind: Service
metadata:
  name: gitea
  namespace: gitea
  labels:
    app: gitea
    app.kubernetes.io/name: gitea
    app.kubernetes.io/instance: gitea
spec:
  type: ClusterIP
  externalIPs:
    - 10.1.132.200
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  - name: http-3000
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/instance: gitea
