apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata:
  name: cucp-regional
  namespace: oai-ran-cucp
spec:
  provider: cucp.openairinterface.org
  interfaces:
  - name: n2
    ipv4:
      address: 10.1.139.60/24
      gateway: 10.1.139.1
    vlanID: 4
  - name: f1c
    ipv4:
      address: 10.1.139.61/24
      gateway: 10.1.139.1
    vlanID: 5
  - name: e1
    ipv4:
      address: 10.1.139.62/24
      gateway: 10.1.139.1
    vlanID: 6
  networkInstances:
  - name: vpc-ran
    interfaces:
    - n2
  - name: vpc-cudu-f1
    interfaces:
    - f1c
  - name: vpc-cu-e1
    interfaces:
    - e1
  parametersRefs:
  - name: cucp-regional-config
    apiVersion: workload.nephio.org/v1alpha1
    kind: NFConfig
  - name: cucp-regional-amf-central
    apiVersion: ref.nephio.org/v1alpha1
    kind: Config
