apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata:
  name: udr-core
  namespace: exp1-a
  labels:
    app.kubernetes.io/part-of: ina-infra
    app.kubernetes.io/component: dedicated-core
spec:
  provider: udr.openairinterface.org
