apiVersion: v1
kind: ServiceAccount
metadata:
  name: application-ott
  namespace: exp1-a
  labels:
    app.kubernetes.io/name: application-ott
    app.kubernetes.io/part-of: ina-infra
    ina.lab/slice: '3'
    ina.lab/app-type: ott
    ina.lab/role: server
