apiVersion: v1
data:
  secretkey: OFpqT2hvMk5qbzBSeElWdGxnR3BhZw==
kind: Secret
metadata:
  labels:
    app.kubernetes.io/managed-by: configmanagement.gke.io
  name: memberlist
  namespace: metallb-system
type: Opaque
