apiVersion: v1
kind: ServiceAccount
metadata:
  name: application-physical-ai
  namespace: exp1-a
  labels:
    app.kubernetes.io/name: application-physical-ai
    app.kubernetes.io/part-of: ina-infra
    ina.lab/slice: '2'
    ina.lab/app-type: physical_ai
    ina.lab/role: server
