apiVersion: apps/v1
kind: Deployment
metadata:
  name: openspeedtest
  namespace: default
  labels:
    app: openspeedtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openspeedtest
  template:
    metadata:
      labels:
        app: openspeedtest
    spec:
      containers:
      - name: openspeedtest
        image: openspeedtest/latest:latest
        ports:
        - containerPort: 3000 # HTTP Port
        - containerPort: 3001 # HTTPS Port
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: openspeedtest-service
  namespace: default
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.1.132.50
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  selector:
    app: openspeedtest
  ports:
    - name: http
      protocol: TCP
      port: 80         # Standard HTTP Port!
      targetPort: 3000
