apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/ip-allocated-from-pool: site-pool
    metallb.universe.tf/loadBalancerIPs: 10.1.138.126
  name: openspeedtest-service
  namespace: default
spec:
  allocateLoadBalancerNodePorts: false
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: openspeedtest
  sessionAffinity: None
  type: LoadBalancer
