apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    configmanagement.gke.io/managed: enabled
    configmanagement.gke.io/source-path: namespaces/nephio-system/deployment-nephio-controller.yaml
    configmanagement.gke.io/token: fa352451d6fec752b063f38b22c05ecb5aeda19c
    configsync.gke.io/git-context: '{"repo":"http://10.1.132.51:3000/nephio/mgmt.git","branch":"main","rev":"HEAD"}'
    configsync.gke.io/manager: :root_mgmt
    configsync.gke.io/resource-id: apps_deployment_nephio-system_nephio-controller
  labels:
    app.kubernetes.io/managed-by: configmanagement.gke.io
    configsync.gke.io/declared-version: v1
  name: nephio-controller
  namespace: nephio-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      fn.kptgen.dev/controller: nephio-controller
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: '2026-06-16T16:26:40Z'
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: tbd
        app.kubernetes.io/instance: tbd
        app.kubernetes.io/managed-by: kpt
        app.kubernetes.io/name: nephio
        app.kubernetes.io/part-of: nephio
        app.kubernetes.io/version: tbd
        fn.kptgen.dev/controller: nephio-controller
      name: nephio-controller
      namespace: nephio-system
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: quay.io/brancz/kube-rbac-proxy:v0.8.0
        imagePullPolicy: IfNotPresent
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        command:
        - /manager
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: NODE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: GIT_URL
          value: http://gitea.gitea.svc.cluster.local:3000
        - name: GIT_NAMESPACE
          value: gitea
        - name: ENABLE_APPROVAL
          value: 'true'
        - name: ENABLE_REPOSITORIES
          value: 'true'
        - name: ENABLE_BOOTSTRAPSECRETS
          value: 'true'
        - name: ENABLE_BOOTSTRAPPACKAGES
          value: 'true'
        - name: ENABLE_GENERICSPECIALIZER
          value: 'true'
        - name: ENABLE_NETWORKS
          value: 'true'
        - name: CLIENT_PROXY_ADDRESS
          value: resource-backend-controller-grpc-svc.backend-system.svc.cluster.local:9999
        image: docker.io/nephio/nephio-operator:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        name: controller
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: nephio-controller
      serviceAccountName: nephio-controller
      terminationGracePeriodSeconds: 30
