apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-cu-up-1
  namespace: oai-slice-deployment
  labels:
    app.kubernetes.io/name: oai-cu-up-1
    slice: '1'
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: oai-cu-up-1
  template:
    metadata:
      labels:
        app: oai-cu-up-1
        app.kubernetes.io/name: oai-cu-up-1
        slice: '1'
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{"name": "cuup-slice1-e1", "interface": "e1",
          "ips": ["10.1.139.70/24"], "gateways": ["10.1.139.1"]}, {"name": "cuup-slice1-f1u",
          "interface": "f1u", "ips": ["10.1.139.71/24"], "gateways": ["10.1.139.1"]},
          {"name": "cuup-slice1-n3", "interface": "n3", "ips": ["10.1.139.72/24"],
          "gateways": ["10.1.139.1"]}]'
        oai.nephio.org/upf-n3: 10.1.139.20
        oai.nephio.org/site: central
    spec:
      serviceAccountName: oai-cu-up-1-sa
      terminationGracePeriodSeconds: 5
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - central-0
                - central-1
      containers:
      - name: cuup
        image: 10.1.132.30:5000/oai-nr-cuup:nws-v0.8-amd64
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        env:
        - name: TZ
          value: Europe/Paris
        - name: USE_ADDITIONAL_OPTIONS
          value: --log_config.global_log_options level,nocolor,time
        - name: USE_VOLUMED_CONF
          value: 'yes'
        ports:
        - name: n3
          containerPort: 2152
          protocol: UDP
        - name: e1
          containerPort: 38462
          protocol: SCTP
        volumeMounts:
        - name: configuration
          mountPath: /opt/oai-gnb/etc/gnb.conf
          subPath: gnb.conf
      - name: debug
        image: docker.io/nicolaka/netshoot
        command:
        - sleep
        - infinity
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
      volumes:
      - name: configuration
        configMap:
          name: oai-cu-up-1-configmap
