apiVersion: v1
kind: Service
metadata:
  name: sliced-edge
  namespace: oai-slice-deployment
  labels: &id001
    app.kubernetes.io/name: sliced-edge
spec:
  type: ClusterIP
  externalIPs:
  - 10.1.132.210
  selector: *id001
  ports:
  - name: mqtt
    port: 1883
    targetPort: 1883
    protocol: TCP
  - name: metrics
    port: 9105
    targetPort: 9105
    protocol: TCP
