apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/ip-allocated-from-pool: local-pool
    metallb.universe.tf/loadBalancerIPs: 10.1.137.61
  labels:
    app: open5gs-5gc
  name: open5gs-5gc
  namespace: open5gs
spec:
  allocateLoadBalancerNodePorts: false
  externalTrafficPolicy: Local
  ports:
  - name: webui
    port: 9999
    protocol: TCP
    targetPort: 9999
  - name: ngap
    port: 38412
    protocol: SCTP
    targetPort: 38412
  - name: gtpu
    port: 2152
    protocol: UDP
    targetPort: 2152
  selector:
    app: open5gs-5gc
  sessionAffinity: None
  type: LoadBalancer
