apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.1.132.52
  labels:
    app: nephio-webui
    app.kubernetes.io/instance: nephio-webui
    app.kubernetes.io/managed-by: configmanagement.gke.io
    app.kubernetes.io/name: nephio-webui
  name: nephio-webui
  namespace: nephio-webui
spec:
  allocateLoadBalancerNodePorts: false
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: nephio-webui
  sessionAffinity: None
  type: LoadBalancer
