apiVersion: v1
kind: Namespace
metadata:
  name: exp4-s3
  labels:
    app.kubernetes.io/name: exp4-s3
    app.kubernetes.io/part-of: exp4
    ina.lab/scheme: exp4-s3
    ina.lab/pl: "true"
    ina.lab/pm: "true"
    ina.lab/ps: "true"
