apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-gnb
  namespace: oai-nws-1ue
  labels:
    app.kubernetes.io/name: oai-gnb
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: oai-gnb
  template:
    metadata:
      labels:
        app: oai-gnb
        app.kubernetes.io/name: oai-gnb
      annotations:
        k8s.v1.cni.cncf.io/networks: "[\n {\n  \"name\": \"gnb-n2n3\",\n  \"interface\"\
          : \"n2\",\n  \"ips\": [\"10.1.139.113/24\"],\n  \"gateways\": [\"10.1.139.1\"\
          ]\n }\n]"
    spec:
      serviceAccountName: oai-gnb-sa
      terminationGracePeriodSeconds: 5
      nodeSelector:
        kubernetes.io/hostname: usrp
      containers:
      - name: gnb
        image: 10.1.132.30:5000/oai-gnb:nws-v0.2
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        env:
        - name: USE_ADDITIONAL_OPTIONS
          value: -E --rfsim --log_config.global_log_options level,nocolor,time
        ports:
        - name: n2
          containerPort: 38412
          protocol: SCTP
        - name: n3
          containerPort: 2152
          protocol: UDP
        - name: rfsim
          containerPort: 4043
          protocol: TCP
        resources:
          requests:
            cpu: 2000m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 2Gi
        volumeMounts:
        - name: configuration
          mountPath: /opt/oai-gnb/etc/gnb.conf
          subPath: gnb.conf
      - name: debug
        image: docker.io/nicolaka/netshoot
        command:
        - sleep
        - infinity
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
      volumes:
      - name: configuration
        configMap:
          name: oai-gnb-configmap
