apiVersion: v1
kind: ConfigMap
metadata:
  name: oai-udr-op-conf
  namespace: oai-cn-operators
data:
  udr.yaml: "ports:\n  - name: 'http'\n    port: 80\n    protocol: TCP\nnfInterfaces:\n\
    \  sbi: 'eth0'\ncompute:\n  req:\n    cpu: '100m'\n    memory: '512Mi'\n  limits:\n\
    \    cpu: '100m'\n    memory: '512Mi'\nlogLevel: info\nimage: 'docker.io/oaisoftwarealliance/oai-udr:v2.0.1'\n\
    fqdn:\n  nrf: '10.1.140.11'\ndatabase:\n  host: mysql\n  type: mysql\n  user: test\n\
    \  pass: test\n  connection_timeout: 300 # seconds\n"
