apiVersion: v1
kind: Service
metadata: # kpt-merge: nephio-webui/nephio-webui
  name: nephio-webui
  namespace: nephio-webui
  labels:
    app: nephio-webui
    app.kubernetes.io/name: nephio-webui
    app.kubernetes.io/instance: nephio-webui
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.1.132.52
    internal.kpt.dev/upstream-identifier: '|Service|nephio-webui|nephio-webui'
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  selector:
    app: nephio-webui
  ports:
    - name: http
      port: 80
      targetPort: http
